/*
 * Sev_config.c
 *
 *  Created on: ??þ/??þ/????
 *      Author: nada8
 */

#include "stdTypes.h"
#include "errorStates.h"

#include "DIO_int.h"

#include "Sev_priv.h"
#include "Sev_config.h"

 u8 SEG_u8AsSeg[]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6f};

SEG_t SEG_AstrSegConfig[SEG_NUM]={
		{DIO_PORTA,PIN0,DIO_PORTB,PIN1,DIO_PORTC,PIN2,DIO_PORTD,PIN3,DIO_PORTA,PIN4,DIO_PORTB,PIN5,DIO_PORTC,PIN6,NOT_CONNECTED,NOT_CONNECTED,NOT_CONNECTED,NOT_CONNECTED,COMMON_ANODE},
		{DIO_PORTA,PIN7,DIO_PORTB,PIN6,DIO_PORTC,PIN5,DIO_PORTD,PIN4,DIO_PORTA,PIN3,DIO_PORTB,PIN2,DIO_PORTC,PIN1,NOT_CONNECTED,NOT_CONNECTED,NOT_CONNECTED,NOT_CONNECTED,COMMON_CATHODE},
};
